# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 285bc422bc3a7da6d9a115802ef0ff8d92b637d1

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 4f6b265d2e3a0c3b5a71f2999fa7e01f013539e3

{
  "title": "Холодильник",
  "description": "Морозит"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/5/
Content-Type: application/json
Authorization: Token 4f6b265d2e3a0c3b5a71f2999fa7e01f013539e3

{
    "title": "Мотоцикл",
  "description": "Мощный",
  "status": "OPEN",
  "draft": "False"
}

###

# попытка удалить объвление
DELETE  {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 4f6b265d2e3a0c3b5a71f2999fa7e01f013539e3

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-10-21
Content-Type: application/json
