# Generated by Django 4.1.1 on 2022-09-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
