# Generated by Django 4.1.1 on 2022-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_measurement_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
